name: Publish to PyPI
on:
  release:
    types: [ published ]

jobs:
  publish_to_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: get version from tag
        id: get_version
        run: |
          realversion="${GITHUB_REF/refs\/tags\//}"
          realversion="${realversion//v/}"
          echo "::set-output name=VERSION::$realversion"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          pip install -r dev_requirements.txt

      - name: Build package
        run: |
          python setup.py build
          python setup.py sdist bdist_wheel

      - name: Publish to Pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
